# Generated by Django 2.0 on 2018-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_insest',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
